import { Metadata } from 'next';
import Link from 'next/link';
import Header from '@/components/Header';
import { ScalesIcon } from '@/components/icons';
import { ALL_EXAMPLES } from '@/lib/example-complaints';

export const metadata: Metadata = {
  title: 'Legal Complaint Examples | Sample Consumer, RERA & RTI Complaints',
  description: 'Browse sample legal complaints generated by AI Vakeel. See real examples of consumer complaints, RERA complaints, and RTI applications with proper legal format and citations.',
  keywords: [
    'consumer complaint example',
    'RERA complaint sample',
    'RTI application example',
    'legal complaint format India',
    'consumer forum complaint sample',
    'complaint letter format',
  ],
  openGraph: {
    title: 'Legal Complaint Examples | AI Vakeel',
    description: 'Browse sample consumer complaints, RERA complaints, and RTI applications generated by AI Vakeel.',
    url: 'https://aivakeel.in/examples',
    siteName: 'AI Vakeel',
    locale: 'en_IN',
    type: 'website',
  },
  alternates: {
    canonical: 'https://aivakeel.in/examples',
  },
};

function getDomainColor(domain: string): string {
  switch (domain) {
    case 'Consumer Protection':
      return 'bg-blue-100 text-blue-800';
    case 'RERA':
      return 'bg-green-100 text-green-800';
    case 'RTI':
      return 'bg-purple-100 text-purple-800';
    default:
      return 'bg-slate-100 text-slate-800';
  }
}

export default function ExamplesPage() {
  return (
    <div className="min-h-screen flex flex-col bg-cream">
      <Header />

      <main className="flex-1">
        {/* Hero Section */}
        <section className="bg-gradient-to-b from-navy-900 to-navy-800 text-white py-16 px-6">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-extrabold tracking-tight leading-tight">
              Sample Legal Complaints Generated by AI Vakeel
            </h1>
            <p className="mt-6 text-lg md:text-xl text-slate-300 leading-relaxed max-w-3xl mx-auto">
              Browse real examples of consumer complaints, RERA complaints, and RTI applications. See the quality and format of documents our AI generates.
            </p>
          </div>
        </section>

        {/* Examples Grid */}
        <section className="py-16 px-6 bg-white">
          <div className="max-w-5xl mx-auto">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {ALL_EXAMPLES.map((example) => (
                <Link
                  key={example.slug}
                  href={`/examples/${example.slug}`}
                  className="block bg-white rounded-xl p-6 shadow-card border border-slate-100 hover:border-gold-400 hover:shadow-lg transition-all group"
                >
                  <span className={`inline-block px-3 py-1 rounded-full text-xs font-semibold mb-4 ${getDomainColor(example.domain)}`}>
                    {example.domain}
                  </span>
                  <h2 className="text-lg font-bold text-navy-900 mb-3 group-hover:text-gold-600 transition-colors leading-snug">
                    {example.title}
                  </h2>
                  <p className="text-sm text-slate-600 leading-relaxed">
                    {example.description}
                  </p>
                  <div className="mt-4 text-sm font-medium text-gold-500 group-hover:text-gold-600">
                    View Full Document →
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 px-6 bg-gradient-to-b from-navy-900 to-navy-800 text-white text-center">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Generate Your Own Legal Complaint
            </h2>
            <p className="text-slate-300 text-lg mb-8">
              These are just examples. AI Vakeel generates personalized complaints tailored to your specific situation — in minutes, for free.
            </p>
            <Link
              href="/"
              className="inline-flex items-center gap-2 px-8 py-4 bg-gold-400 text-navy-900 font-bold rounded-lg hover:bg-gold-500 transition-colors shadow-gold-glow text-lg"
            >
              <ScalesIcon className="w-5 h-5" />
              Start Generating — Free
            </Link>
          </div>
        </section>

        {/* Internal Links */}
        <section className="py-12 px-6 bg-white border-t border-slate-100">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-xl font-bold text-navy-900 mb-6">Explore by Category</h2>
            <div className="grid md:grid-cols-3 gap-4">
              <Link href="/consumer-complaint" className="block p-4 bg-cream rounded-lg border border-slate-200 hover:border-gold-400 transition-colors">
                <h3 className="font-semibold text-navy-900">Consumer Complaints</h3>
                <p className="text-sm text-slate-600 mt-1">File complaints against companies under Consumer Protection Act 2019.</p>
              </Link>
              <Link href="/rera-complaint" className="block p-4 bg-cream rounded-lg border border-slate-200 hover:border-gold-400 transition-colors">
                <h3 className="font-semibold text-navy-900">RERA Complaints</h3>
                <p className="text-sm text-slate-600 mt-1">File complaints against builders for delayed possession or defects.</p>
              </Link>
              <Link href="/rti-application" className="block p-4 bg-cream rounded-lg border border-slate-200 hover:border-gold-400 transition-colors">
                <h3 className="font-semibold text-navy-900">RTI Applications</h3>
                <p className="text-sm text-slate-600 mt-1">Get information from government departments using RTI Act 2005.</p>
              </Link>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200/60 bg-white/80 backdrop-blur-sm">
        <div className="max-w-5xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2 text-sm text-slate-500">
            <ScalesIcon className="w-4 h-4 text-gold-400" />
            <span className="font-medium text-slate-700">AI Vakeel</span>
            <span className="text-slate-300">|</span>
            <span>Free Legal Complaint Generator</span>
          </div>
          <p className="text-xs text-slate-400">
            This tool generates draft documents only. Always consult a qualified lawyer for legal advice.
          </p>
        </div>
      </footer>
    </div>
  );
}
