export interface ExampleComplaint {
  slug: string;
  title: string;
  domain: string;
  forum: string;
  sectionsCited: string[];
  description: string;
  document: string;
}

export const ALL_EXAMPLES: ExampleComplaint[] = [
  {
    slug: 'consumer-complaint-flipkart-mobile',
    title: 'Consumer Complaint Against Flipkart for Defective Samsung Galaxy S24 Ultra',
    domain: 'Consumer Protection',
    forum: 'District Consumer Disputes Redressal Commission',
    sectionsCited: ['Section 2(7)', 'Section 2(47)', 'Section 39', 'Section 69', 'Section 86'],
    description: 'A real consumer complaint generated by AI Vakeel for a defective Samsung Galaxy S24 Ultra purchased from Flipkart that developed overheating and green screen lines within 10 days, with the seller refusing replacement by falsely claiming physical damage.',
    document: `# BEFORE THE DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION

**Case No.: ___/2024**
**Date of Filing: ___**

---

## PARTIES

**COMPLAINANT:**
Priya Mehta
[Address of the Complainant]

**VERSUS**

**OPPOSITE PARTY:**
Flipkart Internet Private Limited
[Registered Address of Flipkart]

---

## COMPLAINT UNDER THE CONSUMER PROTECTION ACT, 2019

### JURISDICTION STATEMENT

1. That the present complaint is being filed by the Complainant, Priya Mehta, against the Opposite Party, Flipkart, under the provisions of the Consumer Protection Act, 2019.
2. That this Hon'ble District Consumer Disputes Redressal Commission has jurisdiction to entertain the present complaint as the cause of action arises within its territorial jurisdiction and the value of the goods and services and the compensation claimed does not exceed the pecuniary limit of the District Commission.
3. That the Complainant is a 'consumer' within the meaning of Section 2(7) of the Consumer Protection Act, 2019.

---

## FACTS OF THE CASE

1. That on 5th March 2024, the Complainant purchased a Samsung Galaxy S24 Ultra from the Opposite Party, Flipkart, for a sum of Rs. 1,29,999/- (Rupees One Lakh Twenty-Nine Thousand Nine Hundred and Ninety-Nine Only).
2. That within 10 days of the purchase, i.e., within the stipulated period after 5th March 2024, the said phone started experiencing severe overheating issues and the screen developed prominent green lines, rendering the device defective and unfit for use.
3. That the Complainant promptly approached the Flipkart customer care for a replacement of the defective device, as the product was covered under warranty.
4. That on 16th March 2024, the Flipkart customer care refused to replace the phone, falsely and arbitrarily claiming that the damage was due to physical damage caused by the user, despite there being no such physical damage.
5. That the Complainant possesses an unboxing video as irrefutable proof that the device was received in a proper condition and that the defects (overheating and green lines on the screen) developed entirely on their own, without any physical mishandling or misuse by the Complainant.
6. That the Opposite Party's refusal to replace the defective product constitutes a clear deficiency in service and denial of the Complainant's legitimate right to a defect-free product as guaranteed under the Consumer Protection Act, 2019.
7. That the Complainant has suffered significant mental harassment, inconvenience, and wasted time due to the Opposite Party's negligent and unfair conduct.

---

## LEGAL GROUNDS

1. That the Opposite Party is liable under **Section 39 of the Consumer Protection Act, 2019**, which empowers the District Commission to issue orders for relief where goods are found to be defective. Specifically:
   - **(b)** To replace the goods with new goods of similar description which shall be free from any defect;
   - **(c)** To return to the complainant the price, or, as the case may be, the charges paid by the complainant along with such interest on such price or charges as may be decided;
   - **(d)** To pay such amount as may be awarded by it as compensation to the consumer for any loss or injury suffered by the consumer due to the negligence of the opposite party:

2. That the Opposite Party's conduct constitutes an **unfair trade practice** under **Section 2(47)** of the Consumer Protection Act, 2019, as it falsely denied the warranty claim by fabricating the excuse of 'physical damage' without any evidence.

3. That the Complainant is also entitled to a **product liability action** under **Chapter VI of the Consumer Protection Act, 2019**, under **Section 86 (Liability of Product Sellers)**, as Flipkart being the seller of the product is liable if:
   - **(e)** He failed to exercise reasonable care in assembling, inspecting or maintaining such product or he did not pass on the warnings or instructions of the product manufacturer regarding the dangers involved or proper usage of the product while selling such product and such failure was the proximate cause of the harm.

4. That the complaint is filed within the **limitation period of two years** as prescribed under **Section 69 of the Consumer Protection Act, 2019**, and is maintainable.

---

## RELIEF CLAIMED

In view of the facts and circumstances stated above, the Complainant most respectfully prays that this Hon'ble Commission may be pleased to:

(a) **Direct the Opposite Party to refund the full purchase price of Rs. 1,29,999/-** (Rupees One Lakh Twenty-Nine Thousand Nine Hundred and Ninety-Nine Only) along with interest at the rate of ___% per annum from the date of purchase until the date of actual realization;

(b) **Award a sum of Rs. 25,000/-** (Rupees Twenty-Five Thousand Only) as compensation for mental harassment, agony, and wasted time suffered by the Complainant due to the negligent and unfair conduct of the Opposite Party;

(c) **Award the cost of the present litigation** to the Complainant;

(d) **Grant any other relief** as this Hon'ble Commission may deem fit and proper in the facts and circumstances of the case.

---

## VERIFICATION

I, Priya Mehta, the Complainant above-named, do hereby solemnly verify that the contents of paragraphs 1 to 7 of the complaint are true and correct to my knowledge and belief, that the facts stated in the Legal Grounds section are based on legal advice received and believed to be true, and nothing material has been concealed or misrepresented therefrom.

Verified at ________________ on this _______ day of _____________, 2024.


**DEPONENT (COMPLAINANT)**


_________________________
Priya Mehta


**SOLEMNLY AFFIRMED AND SIGNED BEFORE ME**


_________________________
(Oath Commissioner / Notary Public)

Seal and Signature

---

**Place:** ________________
**Date:** _________________
**Signature of the Complainant:** _________________


**Filed through:**
Advocate for the Complainant
[Name and Enrollment No. of Advocate]
[Address of Advocate's Chamber]`,
  },
  {
    slug: 'rera-complaint-delayed-possession-lucknow',
    title: 'RERA Complaint for Delayed Possession – Skyline Heights, Lucknow',
    domain: 'RERA',
    forum: 'RERA Authority of the concerned state',
    sectionsCited: ['Section 18', 'Section 19', 'Section 31'],
    description: 'A real RERA complaint generated by AI Vakeel against M/s Skyline Developers for failing to deliver possession of a flat in Skyline Heights project, Lucknow, despite full payment of Rs 45 lakh and the agreed possession date having passed.',
    document: `BEFORE THE REAL ESTATE REGULATORY AUTHORITY, [STATE]

**Project:** Skyline Heights  
**Promoter:** M/s Skyline Developers, [Address of Skyline Developers]  
**Allottee:** [Complainant Name], [Complainant Address]  
**RERA Registration Number:** [To be provided]  

**Date of Cause of Action:** 10 March 2023  
**Relief Sought:** Possession of the flat and compensation for delay

---

**This Hon'ble Authority has jurisdiction under Section 31 of the Real Estate (Regulation and Development) Act, 2016 as the complaint pertains to the delay in possession of the flat purchased in the ongoing project Skyline Heights, and the cause of action arose within the geographical limits of [State].**  
**This complaint is being filed within the limitation period of 5 years as prescribed under Section 18 of the Real Estate (Regulation and Development) Act, 2016. The cause of action arose on 10 March 2023.**

---

## MEMORANDUM OF COMPLAINT

1. The complainant [Complainant Name] is an allottee of an apartment in the ongoing project known as Skyline Heights developed by M/s Skyline Developers.  
2. The allotment was made on [date of agreement], and the total cost of the apartment is [total cost].  
3. As per the terms of the agreement, possession was supposed to be handed over by [date of possession].  
4. As of today, 10 March 2023, the promoter has failed to deliver possession of the apartment despite multiple reminders.  
5. The complainant has completed all payment obligations as per the agreement yet has not received any concrete timeline for possession.  
6. The delay in possession has caused significant emotional and financial distress to the complainant.  
7. The promoter has violated the provisions of Section 18 of the Real Estate (Regulation and Development) Act, 2016, which states that if a promoter fails to give possession of the apartment, the allottee is entitled to compensation.  
8. Additionally, the complainant is entitled to a monthly penalty for the delay in possession as per the agreed terms in the contract.

---

## VIOLATIONS

1. Violation of **Section 18**: The promoter has not completed the project or given possession of the apartment as per the agreement.  
2. Violation of **Section 19**: The complainant has rights as an allottee which have not been honored by the promoter due to the delay in possession.

---

## RELIEF SOUGHT

The complainant respectfully requests this Hon'ble Authority to:  
1. Direct M/s Skyline Developers to hand over possession of the apartment immediately.  
2. Award compensation for the delay in possession as per agreements and relevant sections of the RERA Act.  
3. Impose any other fines or penalties as deemed appropriate by this Hon'ble Authority.

---

## LIST OF ANNEXURES
1. Annexure A: Agreement for sale  
2. Annexure B: Payment receipts  
3. Annexure C: Communication records with the promoter  
4. Annexure D: Any other relevant documents

---

**Verification**  
I, [Complainant Name], S/o/D/o [Parent Name], aged [Age] years, resident of [Complainant Address], do hereby solemnly affirm and state that the contents of paragraphs 1 to 8 of this complaint are true and correct to my knowledge and belief. No part of it is false and nothing material has been concealed. Verified at [Place] on this 10th day of March, 2023.

---

## Hindi Prayer Clause

अभिवेदन है कि इस सम्माननीय प्राधिकरण से निवेदन है कि 1. श्रीमान स्काईलाइन डेवलपर्स को तुरंत फ्लैट का कब्जा सौंपने का निर्देश दिया जाए। 2. सौदे और रेरा अधिनियम की संबंधित धाराओं के अनुसार कब्जे में हुई देरी के लिए मुआवजा दिया जाए। 3. इस सम्माननीय प्राधिकरण द्वारा उपयुक्त समझे जाने वाले और किसी अन्य दंड या जुर्माना लगाया जाए.`,
  },
  {
    slug: 'rti-road-construction-budget',
    title: 'RTI Application for Road Repair Budget & Contractor Details – Noida Sector 15',
    domain: 'RTI',
    forum: 'Public Information Officer, Noida Authority',
    sectionsCited: ['Section 6(1)', 'Section 4(1)(b)', 'Section 7(1)', 'Section 19', 'Section 21'],
    description: 'A real RTI application generated by AI Vakeel seeking detailed information about funds allocated and spent on road repair in Sector 15, Noida, including work orders, contractor details, bills paid, and completion certificates for FY 2023-2024.',
    document: `# APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005

---

**To,**

The Public Information Officer
Noida Authority
Noida, Uttar Pradesh

---

## APPLICATION FOR INFORMATION UNDER THE RIGHT TO INFORMATION ACT, 2005

**Application Date:** ________________
**Application No.:** ________________ *(To be assigned)*

---

### DETAILS OF APPLICANT

| Field | Details |
|----|--------|
| **Name** | Amit Verma |
| **Address** | _______________________________________________ |
| **Pincode** | ________________ |
| **Phone** | ________________ |
| **Email** | amit.verma@email.com |
| **Mode of Communication** | Email (Preferred) |

---

### SUBJECT

**Request for information regarding funds allocated and spent by Noida Authority for road repair and maintenance in Sector 15 during the Financial Year 2023–2024.**

---

### DETAILS OF INFORMATION SOUGHT

Shri Amit Verma, the applicant, hereby requests the following specific information under Section 6(1) of the Right to Information Act, 2005, from the office of the Public Information Officer, Noida Authority:

1. **Copy of the detailed budget proposal and allocation** for the financial year 2023–2024 (Period: April 2023 to March 2024) specifically pertaining to road repair and maintenance works in **Sector 15, Noida**.

2. **Copies of all work orders** issued by the Noida Authority for road repair and maintenance in Sector 15 during the period from **April 2023 to March 2024**, including:
   - Date of each work order
   - Scope of work specified
   - Estimated cost mentioned in each work order
   - Department/officer issuing the work order

3. **Complete details of all contractors** engaged for road repair and maintenance in Sector 15 during the aforesaid period, including:
   - Name of the contractor/firm
   - Registration number (if any)
   - Address and contact details of the contractor
   - Name of the responsible person/partner/owner

4. **Copies of all bills paid** by the Noida Authority to contractors for road repair and maintenance works in Sector 15 during the period from **April 2023 to March 2024**, including:
   - Bill numbers and dates
   - Amount paid in each bill
   - Name of the contractor to whom payment was made
   - Cheque/RTGS/NEFT reference numbers
   - Tax deduction details (if any)

5. **Copies of completion certificates** issued for road repair and maintenance works in Sector 15 during the period from **April 2023 to March 2024**, including:
   - Date of completion
   - Name of the inspecting officer
   - Quality assessment remarks
   - Any penalty imposed for delayed or unsatisfactory work

6. **Details of any complaints** received by Noida Authority regarding the condition of roads in Sector 15 during the period from **April 2023 to March 2024**, and the **action taken** on each such complaint.

---

### PERIOD FOR WHICH INFORMATION IS SOUGHT

The information sought pertains to the period from **April 2023 to March 2024** (Financial Year 2023–2024).

---

### MODE OF RECEIVING INFORMATION

The applicant requests that the information be provided via **email to amit.verma@email.com**.

In case the information cannot be provided electronically, the applicant requests hard copies to be dispatched by post to the address mentioned above.

---

### FEE PAYMENT DETAILS

| Particulars | Details |
|------------|--------|
| **Application Fee** | ₹10/- |
| **Mode of Payment** | Indian Postal Order / Demand Draft / Banker's Cheque payable to the Accounts Officer, Noida Authority (or cash paid against proper receipt) |
| **DD/IPO Number** | ________________ |
| **Date of Issue** | ________________ |
| **Drawn on Bank** | ________________ |

I am willing to pay any additional cost for photocopying or other means of providing the information, as intimated by the Public Information Officer, in accordance with the Right to Information (Regulation of Fee and Cost) Rules, 2005.

---

### LEGAL GROUNDS

This application is made under the following provisions of the Right to Information Act, 2005:

- **Section 6(1):** Any person desirous of obtaining information shall make a request in writing or through electronic means to the Public Information Officer of the concerned public authority, accompanied by the prescribed fee.

- **Section 4(1)(b):** Every public authority shall publish, among other things, the budget allocated to each of its agencies, the particulars of all plans, proposed expenditures, and reports on disbursements made, and the particulars of demands for grants.

- **Section 21:** Protection of action taken in good faith.

- **Section 19:** Provision for appeal to the First Appellate Authority and further to the Information Commission.

The applicant submits that roads in Sector 15, Noida, have remained in poor and deplorable condition despite the complainant having lodged multiple complaints with the Noida Authority in good faith. The applicant has reason to believe that either:

(a) The funds allocated for road repair and maintenance in Sector 15 have not been properly utilized;

(b) The work orders have not been issued or carried out in a timely manner; or

(c) The work has been carried out in an unsatisfactory and negligent manner.

The applicant, being a citizen of India, has an inherent right to seek such information under the RTI Act, 2005, to ensure transparency and accountability in the functioning of the Noida Authority.

---

### DECLARATION

I, **Amit Verma**, do hereby declare that:

1. I am a citizen of India.

2. The information sought herein is for the purpose of transparency and accountability of a public authority and not for any vexatious or mala fide purpose.

3. I am willing to pay any additional fee towards the cost of providing the information as may be reasonably determined by the Public Information Officer.

4. I am **not** a person belonging to the Below Poverty Line (BPL) category / *(strike out whichever is not applicable)*.

---

### PRAYER / RELIEF SOUGHT

In view of the above, the applicant most respectfully prays that the Public Information Officer, Noida Authority, may be pleased to:

1. Provide **copies of all work orders** issued for road repair and maintenance in Sector 15 during the period from **April 2023 to March 2024**;

2. Disclose **complete details of all contractors** engaged for the said work, including names, addresses, and registration particulars;

3. Provide **copies of all bills paid** to such contractors during the aforementioned period for road work in Sector 15;

4. Provide **copies of completion certificates** issued for road repair and maintenance works in Sector 15 during the aforesaid period;

5. Provide **details of complaints received and action taken** regarding road conditions in Sector 15 during the period April 2023 to March 2024;

6. Furnish the said information via **email to amit.verma@email.com** within **thirty (30) days** from the receipt of this application, as prescribed under Section 7(1) of the Right to Information Act, 2005;

7. Pass any other order or direction as the Public Information Officer may deem fit and proper in the facts and circumstances of the case.

---

**Place:** ________________

**Date:** ________________

**Yours faithfully,**

&nbsp;

**(Amit Verma)**
Applicant

---

### LIST OF ENCLOSURES

1. Copy of the prescribed application fee (₹10/-
   by Indian Postal Order / Demand Draft / Banker's Cheque / Cash receipt)
2. Copy of identity proof of the applicant (Aadhaar Card / Voter ID / PAN Card)
3. Copy of any previous complaint(s) made to Noida Authority regarding road conditions in Sector 15
4. Any other relevant document supporting the application

---

*NOTES:*
- *This application must be replied to within 30 days of receipt under Section 7(1) of the RTI Act, 2005. In case the information concerns the life or liberty of a person, it must be provided within 48 hours.*
- *In case of refusal or non-response, the applicant has the right to file an appeal before the First Appellate Authority of Noida Authority within 30 days of the expiry of the prescribed period or receipt of the decision, under Section 19(1) of the RTI Act, 2005.*
- *A second appeal before the State Information Commission, Uttar Pradesh, can be filed under Section 19(3) within 90 days.*`,
  },
];
